name: CI

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Build linux
      run: npm run build:linux  
    - name: Upload to Release
      uses: JasonEtco/upload-to-release@v0.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: dist/explorer3_1.0.0_amd64.deb

        

