name: CI

on: [release]

jobs:
  build-linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install bluetooth
      run: sudo apt-get install -y build-essential libbluetooth-dev
    - name: Install dependencies
      run: npm install
    - name: Build linux
      run: npm run build:linux  
    - name: Creating out
      run: | 
        mkdir out
        cp dist/linux.AppImage out/
        cp dist/linux.deb out/
        
    - name: Upload build
      uses: actions/upload-artifact@master
      with:
        name: linux
        path: out
  build-mac:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: Install dependencies
      run: npm install
    - name: Build mac
      run: npm run build:mac
    - name: Creating out
      run: | 
        mkdir out
        cp dist/mac.pkg out/
    - name: Upload build
      uses: actions/upload-artifact@master
      with:
        name: mac
        path: out
        
  upload:
    runs-on: ubuntu-latest
    needs: 
    steps:
    - uses: actions/checkout@v1
    - name: Download linux artifact
      uses: actions/download-artifact@master
        with:
          name: linux
          
    - name: Download linux artifact
      uses: actions/download-artifact@master
        with:
          name: mac
      
    - name: Upload to Release deb
      uses: JasonEtco/upload-to-release@v0.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: linux/linux.deb application/vnd.debian.binary-package
        
    - name: Upload to Release AppImage
      uses: JasonEtco/upload-to-release@v0.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: linux/linux.AppImage application/x-executable
        
    - name: Upload to Release pkg
      uses: JasonEtco/upload-to-release@v0.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        args: mac/mac.pkg application/x-xar
        
      

