name: CI

on: [release]

jobs:
  build-linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install bluetooth
      run: sudo apt-get install -y build-essential libbluetooth-dev
    - name: Install dependencies
      run: npm install
    - name: Build linux
      run: npm run build:linux  
    - name: Creating out
      run: | 
        mkdir out
        cp dist/linux.AppImage out/
        cp dist/linux.deb out/
        
    - name: Upload build
      uses: actions/upload-artifact@master
      with:
        name: linux
        path: out
  build-mac:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: Install dependencies
      run: npm install
    - name: Build mac
      run: npm run build:mac
    - name: Creating out
      run: | 
        mkdir out
        cp dist/mac.pkg out/
    - name: Upload build
      uses: actions/upload-artifact@master
      with:
        name: mac
        path: dist
      

